# Generated by Django 2.1.5 on 2019-02-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuorse',
            new_name='Course',
        ),
    ]
